var str = ['Awesome! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ornare, velit a varius viverra, nibh nibh maximus urna, sed bibendum felis nunc quis metus. Praesent lacinia imperdiet massa vitae commodo. Vivamus ullamcorper, turpis sed tincidunt sagittis, quam risus consequat lacus, in consectetur ligula tortor sit amet ligula. Maecenas dolor felis, suscipit ac commodo quis, feugiat a massa. Aliquam faucibus euismod mi, ac dapibus sapien imperdiet quis. Donec ultrices suscipit commodo. Vivamus viverra sollicitudin est faucibus egestas. Cras cursus lectus sed gravida lacinia. Duis volutpat, tortor vitae molestie fringilla, orci justo auctor erat, ut pellentesque nibh turpis nec ante. Nam congue consectetur sem vel auctor. Integer condimentum pharetra ante. Donec ac suscipit purus. Ut sodales fermentum dolor, vel semper turpis pellentesque egestas. Nunc pretium felis arcu, id sollicitudin purus dapibus sit amet. Nullam convallis facilisis neque, sit amet pellentesque velit luctus eu. Nullam mattis eleifend urna non consectetur. ',

	'Pellentesque dictum ultrices egestas. Nullam imperdiet bibendum nisi a aliquet. Nunc bibendum blandit finibus. Ut tincidunt maximus consectetur. Quisque ligula neque, aliquet a dictum at, maximus id dolor. Nullam pellentesque mi eget sem tempor hendrerit. Integer mattis, nisi a tempus ultrices, dolor erat gravida tellus, id facilisis risus dui sit amet diam. Donec id justo molestie, finibus odio nec, volutpat leo. ',

	'<div>Proin et <a href="#">sapien pretium</a> massa mollis pretium eu eu ligula. Donec tincidunt ante lorem, nec condimentum nulla volutpat at. Aliquam sit amet finibus tortor, molestie tincidunt magna. Quisque viverra leo ut eros faucibus, vel convallis lorem dictum. Fusce condimentum purus in consequat imperdiet. Nulla id interdum mi. Nulla felis enim, tempor non orci vitae, luctus dapibus risus. Ut facilisis erat a felis fermentum sollicitudin. Vestibulum at auctor risus, eu interdum diam. Duis sodales ut ipsum vitae placerat. Fusce sed rutrum nulla. Aliquam vel risus at elit auctor luctus rhoncus id augue. Mauris eget nisi vel libero commodo vestibulum dignissim sed lorem.</div>',

	'Duis porttitor erat dui, eget tristique neque laoreet in. Nunc facilisis leo ac lectus elementum, vitae euismod tellus vulputate. Nullam purus urna, suscipit in bibendum et, placerat eget felis. Cras faucibus vehicula lectus. Donec mollis, diam eu congue mollis, massa lectus euismod nulla, id volutpat odio lectus id leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam finibus et elit sit amet iaculis. Pellentesque vulputate feugiat magna in aliquet. Aliquam erat volutpat. Ut sagittis velit hendrerit elementum pellentesque. ',

	'Nulla elit nibh, malesuada a tristique consequat, molestie et leo. Aenean luctus eleifend velit, sit amet dignissim tellus tincidunt in. Integer auctor ut tellus a aliquet. Sed gravida vehicula magna, nec hendrerit justo. Nulla facilisi. Aenean ornare nunc vel ex suscipit porttitor. Praesent sollicitudin in velit eu bibendum. Integer pulvinar vel massa quis mollis. Pellentesque tortor ante, tempor id gravida et, condimentum sagittis sem. Sed porttitor dui ut mi ullamcorper pharetra. Nulla eu elit blandit, viverra sem in, tristique enim. Aenean iaculis neque a sollicitudin tristique. Praesent tincidunt, ipsum quis consequat porttitor, est tellus consequat magna, quis tincidunt urna eros nec leo.'].join(',');

module.exports = str;